### ISSUE TITLE
BeginContainer crashes when XGraphics was created from a pdf page

### ISSUE THREAD

**Issue by fsc-sma** [empira/PDFsharp#123]
## Actual Behavior

With PDFsharp-GDI 6.1.0 the following code crashes:

```
var pdfDocument = new PdfDocument();
var pdfPage = pdfDocument.AddPage();

var xGraphics = XGraphics.FromPdfPage(pdfPage);
var container = xGraphics.BeginContainer();
xGraphics.EndContainer(container);
```

Stacktrace:

```
System.InvalidOperationException : _gfx
   at PdfSharp.Drawing.XGraphics.BeginContainer(XRect dstrect, XRect srcrect, XGraphicsUnit unit)
   at PdfSharp.Drawing.XGraphics.BeginContainer()
```

## Expected Behavior

It should be possible to use containers when XGraphics was created from a pdf page.

**Comment by chrgrwilde** [comment]
Hello guys, 
do see a change to get this bug fixed? This bug keeps us from updating from an old version (1.32). 
Best regards
Christian

**Comment by chrgrwilde** [comment]
Analysing the code, the line throwing this exception came in with https://github.com/empira/PDFsharp/commit/a8fe9093a1d0d0b4639d5c412e959cbb796228f9 / 
https://github.com/empira/PDFsharp/commit/a8fe9093a1d0d0b4639d5c412e959cbb796228f9#diff-cdb5c64e8ac174735489f0b45834e0b37717278dc7c8ba6a4ea201bc5bf9c9e7R4351
#

**Comment by ThomasHoevel** [comment]
Thanks for the feedback. We fixed the bug a while ago and fix will be included in PDFsharp 6.2.0 Preview 2 coming later this year.
