### ISSUE TITLE
PdfDictionary is set but CryptFilterDecodeParms are not initialized correctly

### ISSUE THREAD

**Issue by MarianoJP** [empira/PDFsharp#51]
I am in the process of integrating the PDFsharp Net 6 to my Blazor but am testing it in a separate C# Windows Forms solution. I want to be able to open PDF Forms, fill out the form fields and save it.
While attempting to open the PDF form from a government institution with security restrictions, the program reports the following error:

"Crypt filter value for PdfDictionary is set but CryptFilterDecodeParms are not initialized correctly."

Details are:

System.InvalidOperationException
  HResult=0x80131509
  Message=Crypt filter value for PdfDictionary is set but CryptFilterDecodeParms are not initialized correctly.
  Source=PdfSharp
  StackTrace:
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.GetCryptFilter(PdfDictionary dictionary)
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.DecryptStream(Byte[]& bytes, PdfDictionary dictionary)
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.DecryptDictionary(PdfDictionary dict, Boolean decryptObjectStream)
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.DecryptObject(PdfObject value)
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.DecryptDocument()
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider)
   at PdfSharp.Pdf.IO.PdfReader.Open(String path, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider provider)
   at PdfSharp.Pdf.IO.PdfReader.Open(String path, PdfDocumentOpenMode openMode)
   at PDF_Testing_Ground.Form1.OpenClick(Object sender, EventArgs e) in C:\source\repos\PDF Testing Ground\PDF Testing Ground\Form1.cs:line 16
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

The code used is:

`           
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;

namespace PDF_Testing_Ground
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void OpenClick(object sender, EventArgs e)
        {
            string filename = @"c:\Text\i-130.pdf";
            PdfDocument pdfDocument = PdfReader.Open(filename, PdfDocumentOpenMode.ReadOnly);;
        }
    }
}
`
The PDF file can be obtained from: https://www.uscis.gov/sites/default/files/document/forms/i-130.pdf

**Comment by ThomasHoevel** [comment]
Another, maybe unrelated, issue with encryption:
https://github.com/empira/PDFsharp/issues/54#issue-1991524948

**Comment by MarianoJP** [comment]
I think the issue is related that the PDFs for the Government entity are produced as XFA forms with embed XML data within the PDF for the form data. As far as I can tell from the PDF format specs, the XFA PDF is a dynamic form created with Adobe's AEM Forms Designer.

**Comment by MarianoJP** [comment]
[https://experienceleague.adobe.com/docs/experience-manager-learn/forms/document-services/pdf-forms-and-documents.html](url)

**Comment by martinossendorf** [comment]
PDFsharp Version 6.1.0-preview-1 is now able to load the mentioned PDF file. There were issues regarding object streams in encrypted files and CryptFilters without CryptFilterDecodeParms.
Thanks for reporting the issue!

**Comment by MarianoJP** [comment]
Thank you @martinossendorf. I have cloned the repository and indeed it opens the file. Could you point me in the direction of how to read the XML/XNA? I know that the PDF file has embeded XML which I could parse once I know how PDFSharp handles it. Thank you again.

**Comment by MarianoJP** [comment]
I have located where and how we can access the XML of the XFA form. It is located within the AcroForm.Elements. Below is a sample code on how you can access the XFA, or rather the XDP (XML Data Package).

`
string filename = @"filename path";
PdfDocument pdfDocument = PdfReader.Open(filename, PdfDocumentOpenMode.Import);
PdfAcroForm fm = pdfDocument.AcroForm;
string decodes = "";
if (fm.Elements.ContainsKey("/XFA"))
{
    var PIs = fm.Elements.Values;
    PdfArray w = (PdfArray)PIs.ToArray()[3];
    for (int x = 0; x <= w.Count(); x++)
    {
        if (x > 0)
        {
            if (x % 2 != 0)  //take only odd elements of the array since these have the stream for the xml
            {
                PdfReference pr = (PdfReference)w.Elements[x];
                PdfDictionary pd = (PdfDictionary)pr.Value;
                decodeds += Encoding.UTF8.GetString(pd.Stream.UnfilteredValue);
            }
       }
     }`

From here you have the entire XDP XML in the decodes string for you to use. Thanks again for your help. I will post on a later date here or in GitHub the code to use for extracting and updating information on these forms.
