### ISSUE TITLE
IndexOutOfRangeException when displaying a PNG

### ISSUE THREAD

**Issue by julienrffr** [empira/PDFsharp#79]
Take the HelloWorld program of Core build,
Add:
`var imageStream = File.Open(@"C:\Users\xxx\Downloads\MI6LOGO.png", FileMode.Open, FileAccess.Read);
XImage xImage = XImage.FromStream(imageStream);
gfx.DrawImage(xImage, 0, 0, 100, 100);`
Where MI6LOGO.png is this attached file: 
![MI6LOGO](https://github.com/empira/PDFsharp/assets/90320494/e40055aa-b414-4340-898b-9aabde48408c)
It will throw an IndexOutOfRangeException at line https://github.com/empira/PDFsharp/blob/b28bc3265e0a15302c04b7b91da0d915a591e167/src/foundation/src/PDFsharp/src/PdfSharp/PngLib/RawPngData.cs#L54
because paletteIndex = 1 and data has 0 elements.

Stack trace:
`   at PdfSharp.BigGustave.RawPngData.GetPixelIndex(Int32 x, Int32 y) in D:\gitroot\PDFsharp.net6\src\foundation\src\PDFsharp\src\PdfSharp\PngLib\RawPngData.cs:line 54
   at PdfSharp.BigGustave.Png.GetPixelIndex(Int32 x, Int32 y) in D:\gitroot\PDFsharp.net6\src\foundation\src\PDFsharp\src\PdfSharp\PngLib\Png.cs:line 52
   at PdfSharp.Drawing.Internal.ImageImporterPng.TestPngInfoHeader(StreamReaderHelper stream, ImportedImage ii) in D:\gitroot\PDFsharp.net6\src\foundation\src\PDFsharp\src\PdfSharp\Drawing.Internal\ImageImporterPng.cs:line 307
   at PdfSharp.Drawing.Internal.ImageImporterPng.ImportImage(StreamReaderHelper stream) in D:\gitroot\PDFsharp.net6\src\foundation\src\PDFsharp\src\PdfSharp\Drawing.Internal\ImageImporterPng.cs:line 29`

**Comment by ThomasHoevel** [comment]
I tried your code snippet with the PNG file downloaded from this thread - and everything worked as expected.

**Comment by julienrffr** [comment]
> I tried your code snippet with the PNG file downloaded from this thread - and everything worked as expected.

@ThomasHoevel  With Core build?

I hope also that github image storage does not alter the image by optimizing it. Or your browser.

Your reproduction scenario is visibly different from mine somewhere.

**Comment by ThomasHoevel** [comment]
I can reproduce it now. I thought I was using Core build, but VS used a different build.
So far I don't see an easy fix.

**Comment by ThomasHoevel** [comment]
Issue should be resolved with PDFsharp 6.2.0 Preview 2 if not already fixed with Preview 1.
