### ISSUE TITLE
Cannot open pdf file when SecuritySettings.OwnerPassword is set 

### ISSUE THREAD

**Issue by puwalski** [empira/PDFsharp#88]
If SecuritySettings.OwnerPassword is set, the document should open without asking for a password, and this is how it worked in version 1.5.x (only setting SecuritySettings.UserPassword protects the document from unauthorised opening). Furthermore, the password set in code is not accepted when opening the file - the file simply cannot be opened. When the same password is set for both SecuritySettings.OwnerPassword and SecuritySettings.UserPassword, the password is also rejected when opening the file.

**Comment by TH-Soft** [comment]
Did you try with 6.1.0-preview-1?

**Comment by puwalski** [comment]
I have tried with versions 6.0, 6.1 and 1.5. Only the file created by 1.5 manages to open. I attach the project and the resulting pdfs.
[PdfSecurityTester.zip](https://github.com/empira/PDFsharp/files/14235973/PdfSecurityTester.zip)
[test-PdfSharp-6.1.0.0.pdf](https://github.com/empira/PDFsharp/files/14235976/test-PdfSharp-6.1.0.0.pdf)
[test-PdfSharp-6.0.0.0.pdf](https://github.com/empira/PDFsharp/files/14235978/test-PdfSharp-6.0.0.0.pdf)
[test-PdfSharp-1.50.5147.0.pdf](https://github.com/empira/PDFsharp/files/14235979/test-PdfSharp-1.50.5147.0.pdf)

**Comment by puwalski** [comment]
The interesting thing is that in the "real" application I'm working on, the save fails at all if I set OwnerPassword. There is one difference though: I am saving to a stream, not to a file. In this case, I get the following exception on line `pdfRenderer.PdfDocument.Save(stream, false)`:

System.InvalidOperationException
  HResult=0x80131509
  Message=Nullable object must have a value.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at System.Nullable`1.get_Value()
   at PdfSharp.Pdf.Security.Encryption.PdfEncryptionV1To4.ComputeObjectEncryptionKey(Boolean useAES)
   at PdfSharp.Pdf.Security.Encryption.PdfEncryptionV1To4.GetObjectEncryptionKeyAES()
   at PdfSharp.Pdf.Security.Encryption.PdfEncryptionV1To4.EncryptForEnteredObjectUsingAES(Byte[]& bytes)
   at PdfSharp.Pdf.Security.PdfCryptFilter.EncryptForEnteredObject(Byte[]& bytes)
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptString(Byte[]& bytes)
   at PdfSharp.Pdf.Internal.PdfEncoders.FormatStringLiteral(Byte[] bytes, Boolean unicode, Boolean prefix, Boolean hex, PdfStandardSecurityHandler securityHandler)
   at PdfSharp.Pdf.Internal.PdfEncoders.ToStringLiteral(String text, PdfStringEncoding encoding, PdfStandardSecurityHandler securityHandler)
   at PdfSharp.Pdf.Annotations.PdfLinkAnnotation.WriteObject(PdfWriter writer)
   at PdfSharp.Pdf.PdfDocument.DoSave(PdfWriter writer)
   at PdfSharp.Pdf.PdfDocument.Save(Stream stream, Boolean closeStream)
   at [...].<Worker>d__15.MoveNext() in C:\[...].cs:line 149

**Comment by martinossendorf** [comment]
Sorry, I can't reproduce Your issue by now.
I'm able to open the files You posted as we'll as files created with Your project using with PDFsharp-MigraDoc  6.0.0 and 6.1.0-preview-1 and a file created with Your project ported back to net472 using PDFsharp-Migradoc 1.50.5147. Using Acrobat Reader 2023, these files open correctly without asking for a password.
Did You use another application to open the files? Starting with 6.0.0, PDFsharp by default uses better encryption mechanisms to protect the file. This is PDF encryption version 4 (using AES) with a 128 bit key length. PDFsharp 1.5 used PDF encryption version 2 (RC4) with 128 key length.
For the case Your target application does not support newer PDF encryption, You could try inserting the line
`pdfRenderer.PdfDocument.SecurityHandler.SetEncryptionToV2With128Bits();`
before saving the document.

I also couldn't reproduce Your issue with saving the document to a stream. I can add lines in Your test project to save the documents to stream without getting an exception. Anyway, maybe there is a special case not yet considered in PDFsharp, that leads to this exception. Could You provide more of the code creating the document and maybe setting encryption parameters, that runs before saving the document fails?

**Comment by tobitege** [comment]
Hallo 😃 
in file `PdfEncryptionV1To4.cs`, method `PadPassword(string password)` has this line:
```cs
			int length = password.Length;
```
IF by code e.g. `somePdfDocument.SecuritySettings.UserPassword` gets `null` assigned, the above line causes an exception
(just checked source against current master branch).

**Comment by ThomasHoevel** [comment]
> IF by code e.g. `somePdfDocument.SecuritySettings.UserPassword` gets `null` assigned, the above line causes an exception (just checked source against current master branch).

UserPassword is of type `string`, not type `string?`. Our code does not assume it could be `null` and our compiler assures us it cannot be `null`.   
If you do not need a UserPassword, leave it untouched or set it to `String.Empty` or `""`, not to `null`.
We might change the behavior with release 6.3.

Stack traces do not help much when investigating issues.

See also:   
https://docs.pdfsharp.net/General/Issue-Reporting.html

![Image](https://github.com/user-attachments/assets/23f10f74-39d2-4c65-bed2-660eea7a7f9e)

**Comment by tobitege** [comment]
Hallo Thomas,
a string is a reference type and can be null (no "?" required). If nullable reference types are not enabled, the compiler won't enforce this, and string can still hold a null value at runtime.

**Comment by ThomasHoevel** [comment]
> a string is a reference type and can be null (no "?" required). If nullable reference types are not enabled, the compiler won't enforce this, and string can still hold a null value at runtime.

We know that. But that is not using the library as intended.

**Comment by RaHorusFreak** [comment]
I execute this method prior to save my PDF:

`
private static void SetReadonly(this PdfDocument document)
{
    PdfSecuritySettings securitySettings = document.SecuritySettings;
    //securitySettings.OwnerPassword = Guid.NewGuid().ToString();
    securitySettings.PermitAnnotations = false;
    securitySettings.PermitAssembleDocument = false;
    securitySettings.PermitExtractContent = true;
    securitySettings.PermitFormsFill = false;
    securitySettings.PermitFullQualityPrint = false;
    securitySettings.PermitModifyDocument = false;
    securitySettings.PermitPrint = false;
}
`

`
internal static byte[] SaveArr(this PdfDocument document, bool setReadonly = true)
{
    using(MemoryStream ms = new MemoryStream())
    {
        if(setReadonly)
            document.SetReadonly();
        document.Save(ms);
        return ms.ToArray();
    }
}
`

Then i save the PDF into a MemoryStream (for FileStream happens the same), and none of the permissions on the security settings are been applied. And, if I uncomment //securitySettings.OwnerPassword = Guid.NewGuid().ToString();, i got the same error described @puwalski . I am working on a form PDF.

**Comment by trithagoras** [comment]
> I have tried with versions 6.0, 6.1 and 1.5. Only the file created by 1.5 manages to open. I attach the project and the resulting pdfs. [PdfSecurityTester.zip](https://github.com/empira/PDFsharp/files/14235973/PdfSecurityTester.zip) [test-PdfSharp-6.1.0.0.pdf](https://github.com/empira/PDFsharp/files/14235976/test-PdfSharp-6.1.0.0.pdf) [test-PdfSharp-6.0.0.0.pdf](https://github.com/empira/PDFsharp/files/14235978/test-PdfSharp-6.0.0.0.pdf) [test-PdfSharp-1.50.5147.0.pdf](https://github.com/empira/PDFsharp/files/14235979/test-PdfSharp-1.50.5147.0.pdf)

I've been banging my head against the wall for the last couple of days with this same issue. If I set an owner password then save the document with other default encryption settings (Encryption V4, AES-128, PDF V1.6), then I can open the document just fine in every single PDF viewer I have EXCEPT Microsoft Edge's PDF viewer. In that instance, I'm prompted to enter a password (just as if the document had a user password set), and entering the owner password does not work - nothing works, leading me to believe the file is somehow corrupted.

This is the code I used to encrypt the doc:
```cs
public byte[] EncryptPdf(MemoryStream inputMs, string ownerPassword) {
    using var outputMs = new MemoryStream();

    var document = PdfReader.Open(inputMs, PdfDocumentOpenMode.Modify);

    // set encryption options
    document.SecuritySettings.OwnerPassword = ownerPassword;

    // restrict permissions
    document.SecuritySettings.PermitAnnotations = false;
    document.SecuritySettings.PermitExtractContent = false;
    document.SecuritySettings.PermitModifyDocument = false;
    document.SecuritySettings.PermitPrint = true;

    // Save the encrypted document
    document.Save(outputMs);
    return outputMs.ToArray();
}
```

Which is then being returned by a Web Controller via:
```cs
return controller.File(pdfBytes, "application/pdf", fileName);
```

Just like @puwalski, I am able to open the test PDF generated with v1.5 but not with 6.0 or 6.1. Since the encryption is different between 1.5 and 6.0, I'm lead to believe the issue is related to that.

I tried setting the PDF version to 20 (2.0) and used v5 encryption and that worked again (able to open in MS Edge no problems).

I noticed something very strange though: if I open one of my <v2.0 generated PDFs with a hex editor, I notice the `/Length 128` key-value pair is missing from the Encrypt dictionary and the `/Length 16` key is present in the CF dictionary. Now, this should be completely fine, since in the spec, the field is noted as being (Optional; PDF 1.4; only if V is 2 or 3), in which V is 4, obviously. But, the document has different properties when editing these two KVP:

| Encrypt.Length? | CF.Length? | Can open in MS Edge | Can open in Chrome |
|--------|--------|--------|--------|
| False | False | False | True |
| False | True | False | True |
| True | False | True | True |
| True | True | True | True |

---

The thing is - I'm not smart enough to make any conclusion here. I can't tell if this is a MS Edge problem or if it's a PDFSharp issue or something else entirely. I suppose I'll leave my findings here for someone else to come along and hopefully piece it together!

[aes128-noEnc-noCf.pdf](https://github.com/user-attachments/files/19749511/aes128-noEnc-noCf.pdf)
[aes128-Enc-noCf.pdf](https://github.com/user-attachments/files/19749513/aes128-Enc-noCf.pdf)
[aes128-Enc-Cf.pdf](https://github.com/user-attachments/files/19749510/aes128-Enc-Cf.pdf)
[aes128-NoEnc-Cf.pdf](https://github.com/user-attachments/files/19749512/aes128-NoEnc-Cf.pdf)

**Comment by CrustyCrocket** [comment]
> You could try inserting the line `pdfRenderer.PdfDocument.SecurityHandler.SetEncryptionToV2With128Bits();` before saving the document.

@martinossendorf  Made my day, thanks a lot!
AcrobatReader was not the problem, but all browsers with chromium engine like Edge couldn't open the pdf.

**Comment by ThomasHoevel** [comment]
> The thing is - I'm not smart enough to make any conclusion here.

At this stage, it would be interesting to know if the issue persists with 6.2.0 Preview 3.

It's unclear to me if this thread deals with one, two, or even three different issues.

**Comment by miika-prose** [comment]
I can can confirm that the issue is still there. I just upgraded from 1.5 to 6.2. The only change I made was to disable removed option:
`securitySettings.DocumentSecurityLevel = PdfDocumentSecurityLevel.Encrypted128Bit;`

File is fine in Acrobat Reader and Firefox but ask password in Edge

**Comment by ThomasHoevel** [comment]
> File is fine in Acrobat Reader and Firefox but ask password in Edge

Sounds like an "Edge only" issue. Did you report it to Microsoft?

**Comment by ogiesen** [comment]
I can also confirm that this still happens with Edge. It's also not limited to `OwnerPassword`. Documents protected only with a `UserPassword` also cannot be opened in Edge.  

Using `PdfDocument.SecurityHandler.SetEncryptionToV2With128Bits()` is a feasible workaround.

**Comment by ThomasHoevel** [comment]
> I can also confirm that this still happens with Edge.

Does it happen with the experimental Edge PDF viewer under Edge?  
Does it happen with the experimental Chromium PDF viewer under Edge?

I can confirm that it still sounds like a Microsoft issue.  
Did you report it to Microsoft?

**Comment by atell0143** [comment]
I have already commented on #261, but since this is a similar open issue, I will note it here as well.

I have confirmed that when V4 encryption is applied to a PDF, validation tools such as qpdf and veraPDF detect errors, although general PDF viewers show no issues except Microsoft Edge's PDF viewer.
This does not seem to be specific to Edge.

**Comment by martinossendorf** [comment]
I just checked #261 and could now also open `/V 4` encrypted files with Edge and the other major browsers. The issue seams to be fixed in Edge 143.0.3650.66.
I'll close the issue now.

Please update the applications, the issue occurs with, and contact their developers, if you observe problems with encrypted files without a `/Length` key, or use `PdfDocument.SecurityHandler.SetEncryptionToV2With128Bits()` as a workaround.
For details see my current post in #261.

**Comment by martinossendorf** [comment]
Due to your feedback on #261, we re-investigated the issue.
We analyzed files encrypted with Acrobat and discovered that the `/Length` entry is always set there. As Edge's new PDF viewer is also adobe powered and obviously always expects the entry, it seems advisable to adapt this behavior instead of implementing the PDF reference.
So, the `/Length` entry will be always written with the next PDFsharp version, which will fix the Edge issue.

Regarding the other issues handled in this thread:
* If the "Nullable object must have a value" issue occurs, ensure that you don't set the user or owner password to null.
* @RaHorusFreak, we could not reproduce your issue. If it persists, please provide more information (like PDFsharp version and target framework). We recommend using the IssueSubmissionTemplate (https://docs.pdfsharp.net/General/Issue-Reporting/About.html).

**Comment by martinossendorf** [comment]
We fixed the problem with Edge's new PDF viewer in PDFsharp 6.2.4.
