### ISSUE TITLE
6.1.0-preview-1 errors when opening file in framework 4.8

### ISSUE THREAD

**Issue by zlangner** [empira/PDFsharp#91]
I'm trying out PDFsharp 6.1.0-preview-1 but I'm finding it cannot open a simple PDF. I'm using .net framework net48

## Expected Behavior
That I can open the attached PDF using a filestream like I could in version 1.50.5147
[2_page.pdf](https://github.com/empira/PDFsharp/files/14323742/2_page.pdf)

## Actual Behavior
Exception thrown

```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute

Stack Trace:
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at PdfSharp.Pdf.IO.PdfReader.FinishChildReferences(PdfDictionary dictionary, PdfDocument document, HashSet`1 finishedObjects)
   at PdfSharp.Pdf.IO.PdfReader.FinishItemReferences(PdfItem pdfItem, PdfDocument document, HashSet`1 finishedObjects)
   at PdfSharp.Pdf.IO.PdfReader.FinishReferences(PdfDocument document)
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider)
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, PdfDocumentOpenMode openMode)
```

## Steps to Reproduce the Behavior
``` c#

using (var fs = File.OpenRead(pathToPdfFile))
{
    var valid = PdfReader.TestPdfFile(fs); // works and is valid
    var doc = PdfReader.Open(fs, PdfDocumentOpenMode.Import); // error thrown
}
```

## Additional information
My full use case is very similar to the [Combine Documents Variant 2](https://www.pdfsharp.net/wiki/CombineDocuments-sample.ashx) example from the PDFSharp docs. My actual code is erroring when `XPdfForm.FromStream(stream)` is called but the above code shows the same error since it's happening while opening the file.

**Comment by ThomasHoevel** [comment]
Duplicate:
https://github.com/empira/PDFsharp/issues/70
Fixed in the meantime, but not yet published.

**Comment by zlangner** [comment]
I just wanted to follow up on this. Using 6.1.0-preview-2 all of my use cases now work. Thanks for releasing that!
